Source/OgrenciYoklama/OgrenciYoklama/Areas/Admin/Controllers/DersController.cs
using NHibernate.Linq;
using OgrenciYoklama.Areas.Admin.ViewModels;
using OgrenciYoklama.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OgrenciYoklama.Areas.Admin.Controllers
{
    public class DersController : Controller
    {
        public ActionResult DersEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DersEkle(Ders form)
        {

            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var ders = new Ders()
            {
                ders_adi = form.ders_adi,
                baslangic_tarihi = form.baslangic_tarihi,
                bitis_tarihi = form.bitis_tarihi,
                haftalik_saat = form.haftalik_saat
            };
            Database.Session.Save(ders);
     
            return RedirectToAction("DersListele");
        }
        public ActionResult DersListele()
        {
            var dersler = Database.Session.Query<Ders>();
            return View(new DerslerDersListele() { Dersler = dersler });
        }

        public ActionResult DersSil(int id)
        {
            var ders = Database.Session.Query<Ders>().FirstOrDefault(p => p.ders_id == id);
            Database.Session.Delete(ders);
            Database.Session.Flush();
            return RedirectToAction("DersListele");

        }
    }
}

Source/OgrenciYoklama/OgrenciYoklama/Areas/Admin/Controllers/OgrenciController.cs
using NHibernate.Linq;
using OgrenciYoklama.Areas.Admin.ViewModels;
using OgrenciYoklama.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System;
using System.Web;

namespace OgrenciYoklama.Areas.Admin.Controllers
{
    
    public class OgrenciController : Controller
    {
        public ActionResult OgrenciListele()
        {
            var ogrenciler = Database.Session.Query<Ogrenci>();
            return View(new OgrencilerOgrenciListele() { Ogrenciler = ogrenciler });
        }

        public ActionResult OgrenciEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult OgrenciEkle(Ogrenci form)
        {

            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var ogrenci = new Ogrenci()
            {
                ogrenci_no = form.ogrenci_no,
                ogrenci_ad = form.ogrenci_ad,
                ogrenci_soyad = form.ogrenci_soyad,
                ogrenci_bolum = form.ogrenci_bolum
            };
            Database.Session.Save(ogrenci);
            return RedirectToAction("OgrenciListele");
        }

       
        public ActionResult OgrenciSil(int id)
        {
            var ogrenci = Database.Session.Query<Ogrenci>().FirstOrDefault(p => p.ogrenci_id == id);
            Database.Session.Delete(ogrenci);
            Database.Session.Flush();
            return RedirectToAction("OgrenciListele");
            
        }
        
    }
}

Source/OgrenciYoklama/OgrenciYoklama/Areas/Admin/Controllers/YoklamaController.cs
using NHibernate.Linq;
using OgrenciYoklama.Areas.Admin.ViewModels;
using OgrenciYoklama.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OgrenciYoklama.Areas.Admin.Controllers
{
    public class YoklamaController : Controller
    {
        // GET: Admin/Yoklama
        public ActionResult Index()
        {
            //  var dersler = Database.Session.Query<Ders>();
            //  ViewBag.YoklamaId = new DerslerDersListele() { Dersler = dersler };
            OgrenciDers ogrders = new OgrenciDers();

            var ogrenciler = Database.Session.Query<Ogrenci>();
            var ogr = new OgrencilerOgrenciListele()
            {
                Ogrenciler = ogrenciler
            };
            ogrders.Ogrenciler = ogr.Ogrenciler;
            var dersler = Database.Session.Query<Ders>();
            var drs = new DerslerDersListele()
            {
                Dersler = dersler
            };

            List<SelectListItem> items = new List<SelectListItem>();

          
            foreach (var item in drs.Dersler)
            {
                items.Add(new SelectListItem { Text = item.ders_adi, Value = item.ders_id.ToString()});
            }
            ViewBag.Dersler = items;
            ogrders.Dersler = drs.Dersler;
            return View(ogrders);
        }
    }
}

Source/OgrenciYoklama/OgrenciYoklama/Areas/Admin/Controllers/YoneticiController.cs
using NHibernate.Linq;
using OgrenciYoklama.Areas.Admin.ViewModels;
using OgrenciYoklama.Infrastructure;
using OgrenciYoklama.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace OgrenciYoklama.Areas.Admin.Controllers
{
    
    public class YoneticiController : Controller
    {
        public ActionResult YoneticiListele()
        {
            var yoneticiler = Database.Session.Query<Yonetici>();
            return View(new YoneticilerYoneticiListele() { Yoneticiler = yoneticiler });
                        
        }

        public ActionResult YoneticiEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YoneticiEkle(Yonetici form)
        {

            if (!ModelState.IsValid)
            {
                return View(form);
            }

            var yonetici = new Yonetici()
            {
                yonetici_ad = form.yonetici_ad,
                yonetici_soyad = form.yonetici_soyad,
                kullanici_adi = form.kullanici_adi
                
            };
            yonetici.SetPassword(form.sifre);
            Database.Session.Save(yonetici);
            return RedirectToAction("YoneticiListele");
        }

        public ActionResult YoneticiSil(int id)
        {
            var yonetici = Database.Session.Query<Yonetici>().FirstOrDefault(p => p.yonetici_id == id);
            Database.Session.Delete(yonetici);
            Database.Session.Flush();
            return RedirectToAction("YoneticiListele");

        }
    }
}

Source/OgrenciYoklama/OgrenciYoklama/Areas/Admin/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

@{
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/admin/styles")
</head>
<body style="background:#cecece;">
    <div style="background:#1793d1; font-size:20px; text-align:center; color:#FFF; height:50px; padding-top:12px;">Öğrenci Yoklama Sistemi</a></div>
    <div id="wrap">
        <header>
            <div class="inner relative">
                <a class="logo"><img src="~/Content/images/logo.png"></a>
                <a id="menu-toggle" class="button dark" href="#"><i class="icon-reorder"></i></a>
                <nav id="navigation">
                    <ul id="main-menu">

                        <li class="parent">
                            <a>Yoklama</a>
                            <ul class="sub-menu">
                                <li>@Html.ActionLink("Yoklama Al", "Index", "Yoklama", new { area = "admin" }, new { })</li>


                            </ul>
                        </li>


                        

                        <li class="parent">
                            @Html.ActionLink("Öğrenciler", "OgrenciListele", "Ogrenci", new { area = "admin" }, new { })
                        </li>



                        <li class="parent">
                            @Html.ActionLink("Dersler", "DersListele", "Ders", new { area = "admin" }, new { })
                        </li>


                        <li class="parent">
                            @Html.ActionLink("Yöneticiler", "YoneticiListele", "Yonetici", new { area = "admin" }, new { })
                        </li>



                        <li class="parent">
                            @Html.RouteLink("Çıkış Yap", "LogOff")
                        </li>





                    </ul>
                </nav>
                <div class="clear"></div>
            </div>
        </header>
    </div>
    @RenderBody()
</body>
</html>